apiVersion: v1
kind: Service

metadata:
  name: monitoring-service
  namespace: monitoring

spec:
  selector:
    app: monitoring-app

  type: NodePort

  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30081
